export const LIST_INVENTORY_COLLECTIONS = 'LIST_INVENTORY_COLLECTIONS';
export const LIST_INVENTORY_COLLECTION_DETAILS =
  'LIST_INVENTORY_COLLECTION_DETAILS';
export const ADD_INVENTORY_COLLECTION = 'ADD_INVENTORY_COLLECTION';
export const DELETE_INVENTORY_COLLECTION = 'DELETE_INVENTORY_COLLECTION';
export const UPDATE_INVENTORY_COLLECTION = 'UPDATE_INVENTORY_COLLECTION';
